

spring:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:mem:az_bookstore
    username: sa
    password: sa
  sql:
    init:
      platform: h2