

spring:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:mem:az_bookstore
    username: sa
    password: sa
  sql:
    init:
      platform: h2

accessToken: $2a$12$W/lAX/yFLzh7DDxGIPm9vup4E.uB0h1l.B1aJjQzwwkdoM/FTO2vK