apiVersion: v1
kind: Service
metadata:
  name: az-bookstore-service
spec:
  selector:
    app: az-bookstore-service
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30008
  type: NodePort