apiVersion: v1
kind: Pod
metadata:
  name: az-bookstore-service
  labels:
    app: az-bookstore-service
spec:
  containers:
    - name: az-bookstore-service
      image: azharmobeen/az-bookstore-service:latest
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8080
  restartPolicy: Always
